// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmInYaCuY178ZmiTg-W1EEqHfNleR7cPc',
    appId: '1:302950792718:web:ac8456d240e0251d8f065f',
    messagingSenderId: '302950792718',
    projectId: 'app-database-9b558',
    authDomain: 'app-database-9b558.firebaseapp.com',
    storageBucket: 'app-database-9b558.appspot.com',
    measurementId: 'G-KBC30FL6FG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtHlNozgJ2rYpkNeSBhLxMg5I0xU9EsHo',
    appId: '1:302950792718:android:1ad039b1e50950ca8f065f',
    messagingSenderId: '302950792718',
    projectId: 'app-database-9b558',
    storageBucket: 'app-database-9b558.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_qyzPhCGjNu0MIXkRdmOHgjxeZ3gKdMI',
    appId: '1:302950792718:ios:4b2f77d94ff9ed198f065f',
    messagingSenderId: '302950792718',
    projectId: 'app-database-9b558',
    storageBucket: 'app-database-9b558.appspot.com',
    iosBundleId: 'com.example.firebaseConnect1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_qyzPhCGjNu0MIXkRdmOHgjxeZ3gKdMI',
    appId: '1:302950792718:ios:23a5dd01658e36dc8f065f',
    messagingSenderId: '302950792718',
    projectId: 'app-database-9b558',
    storageBucket: 'app-database-9b558.appspot.com',
    iosBundleId: 'com.example.firebaseConnect1.RunnerTests',
  );
}
